### ISSUE TITLE
Deserialize cells with numbers as strings

### ISSUE THREAD

**Issue by birktj** [tafia/calamine#115]
I am writing some software that deserializes a excel file as a `Vec<HashMap<String, Value>>` where Value is my own internal value type. I do this using the `RangeDeserializer`, with the headers setting set to `true`. However I am running into some problems when my header contains numbers, is deserialized as such, and I get an error about expecting string and getting a number. I guess a simple fix would to use my internal value type which can be deserialized as both a floating point and a string and then manually converting it to a string, however if the header is parsed as a boolean I would have problem there as well. I don't know if this is considered a bug or not, but is there any workaround other than using `Range::rows()` and manually implementing the deserializing.

**Comment by tafia** [comment]
There is no good solution to this problem I think (yet).
What should eventually be done is a proper format cell parsing (which is incomplete at the moment, notably for dates ...).

**Comment by TimoFreiberg** [comment]
I hit the same problem.

I have to parse a sheet where the headers aren't valid rust identifiers.
Since I'm a Rust newbie, I started implementing my own Serde `Visitor` with a `visit_map` implementation in which I called `calamine::DataType::to_string()` on each value.

Then I found out about the `rename` [field attribute](https://serde.rs/field-attrs.html) which would take a lot less code, but fails with number fields.
I tried to use the `deserialize_with` field attribute but couldn't get it working so far (I followed [this tutorial](https://serde.rs/string-or-struct.html))
