### ISSUE TITLE
Why is Seek needed?

### ISSUE THREAD

**Issue by phiresky** [tafia/calamine#164]
[calamine::Reader](https://docs.rs/calamine/0.16.1/calamine/trait.Reader.html) requires the inner Read to also be Seek. 

I'm thinking of using calamine to add support for xlsx and ods to [ripgrep-all](https://github.com/phiresky/ripgrep-all) (see https://github.com/phiresky/ripgrep-all/issues/36). But since there the read files can be in archives, I only have Read but can't seek.

The only reference to actually using the Seek trait I found is here:

https://github.com/tafia/calamine/blob/06996abcc35306448437ed1f7926cee168e38fbc/src/xls.rs#L125-L127

Are there any other uses I'm missing or should basically all of this library work without Seek except for some pretty specific code in here: https://github.com/tafia/calamine/blob/master/src/cfb.rs#L78 , where just from cursory glance it seems like it could be optional.

**Comment by phiresky** [comment]
If I'm understanding correctly, the only use of Seek to get the total file size for a single `Vec::with_capacity(len)` call in the Xls reader. The capacity is also never read back so this seems to be a purely performance optimization?

**Comment by tafia** [comment]
From https://github.com/tafia/calamine/blob/master/src/lib.rs#L155-L156

> // FIXME `Reader` must only be seek `Seek` for `Xls::xls`. Because of the present API this limits
// the kinds of readers (other) data in formats can be read from.

I agree this is definitely suboptimal and we should probably:
- either send the whole file length for xls
- or change `Cfb::new` to accept a `Option<usize>` ... and generate a simple `Vec::new` here

**Comment by phiresky** [comment]
Ok I just tried to remove all references to Seek to see what happens, but it turns out that [zip::read::ZipArchive](https://docs.rs/zip/0.5.4/zip/read/struct.ZipArchive.html) also requires Seek, which is used in basically all readers (xlsx and ods). 

It is possible to construct a ZipFile from a stream without Seek using [read_zipfile_from_stream](https://docs.rs/zip/0.5.4/zip/read/fn.read_zipfile_from_stream.html), which is what [I do here](https://github.com/phiresky/ripgrep-all/blob/master/src/adapters/zip.rs#L61), but accordin to the docs _some information will be missing when reading this manner_.

So it would need further investigation if that would be a viable option for this crate.

**Comment by jg-kammerer** [comment]
I've delved slightly into zip file format specifically for xlsx, it seems the lost info is not very important in this case. 

A zip archive internally stores individual files. A zip archive can store *comments*, either global to the archive or on a per file basis. Those comments reside in the central directory of the archive, which must be seeked to get the comments. 

Calamine doc (and code agrees) says that missing info using read_zipfile_from_stream are: 
* archive comment or individual file comments, because of the seek (not used by xlsx/ods files, cf below)
* Unix permissions (not needed for xlsx nor ods internal files)
* data_start offset, mostly useful to get an individual file specifically (not needed to grep content of xlsx/ods files)

The good news are : 
* If they were really needed, archive comments or individual file comments are stored basically as a plaintext string in the .zip file (with option to store it as an UTF-8 string) so is greppable directly from the .zip binary (see the output of 'strings the_archive.zip' and compare to 'unzip -l the_archive.zip' which shows comments and file list)
* I have yet to see an .xlsx (didn't check with .ods) file which would use specifically the zip archive comments. Since both xlsx and ods use their own xml index to store file metadata it would make no sense to use the old, size-limited, encoding-unfriendly except perhaps UTF8 zip comments.

I hope this can be useful to add the support of xlsx/ods into ripgrep-all.

**Comment by tafia** [comment]
I noticed that zip crate now supports readers without `Seek`. If anyone is interested to try? Else I'll do it if I manage to find some time but it is very low on my priority list.
